bin/add-exercise
@BNAndras This can be helpful when adding new exercises.
=> Create script to add exercise

bin/verify-exercises
=> ci: fix verify-exercises

exercises/practice/rna-transcription/.meta/src/example.art, exercises/practice/rna-transcription/src/rna-transcription.art, exercises/practice/rna-transcription/tests/test-rna-transcription.art
I thought your `toRna` was a good suggestion
=> rna-transcription: use `toRna`

exercises/practice/resistor-color/tests/test-resistor-color.art
CI fails because result is undefined.
=> Update variables in resistor-color tests

bin/verify-exercises
=> Stop CI after failing exercise

config.json, exercises/practice/space-age/.docs/instructions.md, exercises/practice/space-age/.docs/introduction.md, exercises/practice/space-age/.meta/config.json, exercises/practice/space-age/.meta/src/example.art, exercises/practice/space-age/.meta/tests.toml, exercises/practice/space-age/src/space-age.art, exercises/practice/space-age/tester.art, exercises/practice/space-age/tests/test-space-age.art
=> Add space-age

config.json, exercises/practice/binary-search/.docs/instructions.md, exercises/practice/binary-search/.docs/introduction.md, exercises/practice/binary-search/.meta/config.json, exercises/practice/binary-search/.meta/src/example.art, exercises/practice/binary-search/.meta/tests.toml, exercises/practice/binary-search/src/binary-search.art, exercises/practice/binary-search/tester.art, exercises/practice/binary-search/tests/test-binary-search.art
=> Add binary search

docs/SNIPPET.txt
Here's an idea for the snippet. The `.with:""` part isn't necessary for the join, but we might as well show off attributes. Thoughts? We could workshop something else. There are quite a few Arturo solutions at https://rosettacode.org/wiki/Category:Arturo that we might be able to adapt as long as they're short.
=> Add snippet

config.json
We have a working test runner per https://github.com/exercism/arturo-test-runner/pull/18 so this should be turned on for testing once any other necessary work is done.
=> Turn on test runner

config.json
We have a plugin at https://github.com/exercism/highlightjs-arturo so the staff needs to work their usual magic to hook this up. :)
=> Add highlightjs syntax highlighting

.github/workflows/no-important-files-changed.yml
See https://forum.exercism.org/t/no-important-files-changed-action-not-firing/13673
=> Test no imprtant files changed workflow

.github/workflows/no-important-files-changed.yml
Reverts #100 since testing is done
=> Restore no important files changed main branch

docs/INSTALLATION.md
Closes https://github.com/exercism/arturo/issues/114
=> Remove outdated section

docs/SNIPPET.txt
Updated snippet using the one from our current header @ https://arturo-lang.io
Fixes: #119
=> Updated SNIPPET.txt

config.json
I'm sorting exercises by binned difficulty (1-3, 4-6, 7-10) and then exercise name.
=> Sort exercises in track config

docs/TESTS.md
#148 wasn't a complete revert. My apologies.
=> Remove additional unitt version from docs

docs/TESTS.md
=> Fix markdown link in TESTS.md

exercises/practice/allergies/.meta/config.json, exercises/practice/flatten-array/.docs/instructions.md, exercises/practice/flatten-array/.docs/introduction.md, exercises/practice/flatten-array/.meta/tests.toml, exercises/practice/flatten-array/tests/test-flatten-array.art, exercises/practice/grains/.docs/instructions.md, exercises/practice/grains/.docs/introduction.md, exercises/practice/robot-simulator/.meta/config.json, exercises/practice/sieve/.docs/instructions.md, exercises/practice/strain/.meta/config.json
=> Sync problem-specs

exercises/practice/etl/tests/test-etl.art, exercises/practice/secret-handshake/.meta/config.json, exercises/practice/secret-handshake/.meta/src/example.art
=> Update example solutions for CI

exercises/practice/space-age/.docs/instructions.append.md
Add a level-2 header.
Add a link to the `to` function in the note block.
This is a tiny amount of rep.
=> Update space-age instructions.append doc

config.json
Sorted with 
```bash
jq '.exercises.practice |= sort_by([.difficulty, .name])' config.json | sponge config.json
```
=> Rework exercise difficulties

config.json, exercises/practice/tournament/.docs/instruction.append.md, exercises/practice/tournament/.docs/instructions.md, exercises/practice/tournament/.meta/config.json, exercises/practice/tournament/.meta/src/example.art, exercises/practice/tournament/.meta/tests.toml, exercises/practice/tournament/src/tournament.art, exercises/practice/tournament/tester.art, exercises/practice/tournament/tests/test-tournament.art
=> Tournament

exercises/practice/etl/.docs/instructions.append.md
=> Instructions append for ETL
